name: Docker Image Deploy API-IDENTITY

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  DOCKER_IMAGE_NAME: 'github-actions-docker-identity'
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./src/Services/Identity/Identity.Api/Dockerfile --tag '${{env.DOCKER_IMAGE_NAME}}':latest
